name: squidpy38
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip>=20.3.3
- conda>=4.9.2
- jupyterlab_code_formatter
- black
- isort
- pip:
    - --find-links https://storage.googleapis.com/jax-releases/libtpu_releases.html
    - jax[tpu]==0.3.17
    - -r requirements_tpu.txt
    - -r requirements-dev.txt
